permalink: /:year/:month/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
markdown: rdiscount
paginate: 7
safe: true
future: false
timezone: Asia/Shanghai

title : 岁月留痕
keywords: "财务,葛豪武,个人主页,会计,相册,Accounting,Finance,FreeBSD,Ge Haowu,Haowu Ge,HTML5,Homepage"
description : "人生就像那旅程,谁知道转弯后的风光"
url : https://www.gehaowu.com/life

# 社交网络
social: 
  github: https://github.com/ghw
  twitter: https://twitter.com/ghw
  weixin: #
  tqq: http://t.qq.com/#
  weibo: http://weibo.com/#
  instagram: https://instagram.com/#
  zhihu: http://www.zhihu.com/people/
  v2ex: https://www.v2ex.com/member/
  rss: /atom.xml

analytics: 
#  baidu: false
  google: UA-65013365-1

common: 
  duoshuo: gehaowu

# 作者信息
author :
  name : Haowu Ge
  email : qq@qq.com
  github : ghw
  twitter : ghw


JB :
  BASE_PATH : /life
  ASSET_PATH : false
  archive_path: /archives.html
  about_path: /about.html
  links_path: /links/
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  sitemap_path : /sitemap.xml
  search_path : /search.html
  guestbook_path : /guestbook/
