permalink: /:year/:month/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
markdown: rdiscount
paginate: 7
safe: true
future: false
timezone: Asia/Shanghai

title : Life Memory
keywords: "生活,记忆,生活记忆,Life,Memory,Life Memory,不给力的面条,面条,人生就像那旅程,谁知道转弯后的风光"
description : "人生就像那旅程,谁知道转弯后的风光"
url : http://mt.hexoer.tk

# 社交网络
social: 
  github: https://github.com/ghw
  twitter: https://twitter.com/ghw
  weixin: #
  tqq: http://t.qq.com/#
  weibo: http://weibo.com/#
  instagram: https://instagram.com/#
  zhihu: http://www.zhihu.com/people/
  v2ex: https://www.v2ex.com/member/
  rss: /atom.xml

analytics: 
  baidu: 2f0f4b0d867163a00886350ad2c21f8c

# 作者信息
author :
  name : Haowu Ge
  email : qq@qq.com
  github : ghw
  twitter : ghw


JB :
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archives.html
  about_path: /about.html
  links_path: /links.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml
  sitemap_path : /sitemap.xml
  search_path : /search.html
  guestbook_path : /guestbook.html
